FROM node:13-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm ci --silent --no-optinal
RUN npm install react-scripts -g --silent
COPY . ./
RUN npm run build

FROM nginx:1.19.0-alpine
COPY --from=build /app/build/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
