version: '3.7'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend/:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    env_file: .env
    stdin_open: true

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/app'
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG=1
    env_file: .env
    restart: on-failure

volumes:
  frontend:
  backend: