version: '3.4'

services:
  backend:
    container_name: backend
    image: backend:development
    build:
      context: backend
      dockerfile: Dockerfile
    entrypoint: /bin/sh
    command: -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_DEBUG: 1
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000

  frontend:
    container_name: frontend
    image: frontend:development
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
    stdin_open: true
    ports:
      - 3000:3000
